
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-08
owner: ucsb-cs156-s26
repo_name: team01-s26-08
pull_requests: [{"author":{"id":"U_kgDOB-HICA","is_bot":false,"login":"taedonreth","name":"Taedon Reth"},"headRefName":"tr-Articles-getbyid","number":70,"title":"Add GET by id endpoint for Articles","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/70"},{"author":{"id":"U_kgDOCVHlaQ","is_bot":false,"login":"riasingh455","name":""},"headRefName":"recommend-put","number":69,"title":"Recommend put","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/69"},{"author":{"id":"U_kgDOB-HICA","is_bot":false,"login":"taedonreth","name":"Taedon Reth"},"headRefName":"tr-Articles-controller","number":68,"title":"Add ArticlesController with GET /all and POST /post endpoints","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/68"},{"author":{"id":"U_kgDOB-HICA","is_bot":false,"login":"taedonreth","name":"Taedon Reth"},"headRefName":"tr-Articles-create-db","number":67,"title":"Add Articles entity, repository, and Liquibase migration","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/67"},{"author":{"id":"U_kgDOCVPcVQ","is_bot":false,"login":"matthewli10","name":""},"headRefName":"matthewli-fix-orgCode","number":66,"title":"Use orgCode instead of ID","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/66"},{"author":{"id":"U_kgDOCVHlaQ","is_bot":false,"login":"riasingh455","name":""},"headRefName":"recommend-get-by-id","number":65,"title":"Recommend - get by id","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/65"},{"author":{"id":"U_kgDOCVHlaQ","is_bot":false,"login":"riasingh455","name":""},"headRefName":"Recommend-create-controller","number":64,"title":"Recommend create controller","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/64"},{"author":{"id":"U_kgDOCVHlaQ","is_bot":false,"login":"riasingh455","name":""},"headRefName":"02-RecommendationRequest-create-db","number":63,"title":"create database table - issue2","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/63"},{"author":{"id":"U_kgDOCVHSBA","is_bot":false,"login":"dev-anj","name":"Anjali Dev"},"headRefName":"menuitemreview-delete","number":62,"title":"Menuitemreview delete","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/62"},{"author":{"id":"U_kgDOCVHSBA","is_bot":false,"login":"dev-anj","name":"Anjali Dev"},"headRefName":"menuitemreview-put","number":61,"title":"Menuitemreview PUT","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/61"}]
