
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-08
owner: ucsb-cs156-s26
repo_name: team01-s26-08
pull_requests: [{"author":{"id":"U_kgDOCVPcVQ","is_bot":false,"login":"matthewli10","name":""},"headRefName":"matthewli-delete-endpoint","number":54,"title":"ML - Add DELETE endpoint for a specific record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/54"},{"author":{"id":"U_kgDOCVHSBA","is_bot":false,"login":"dev-anj","name":"Anjali Dev"},"headRefName":"MenuItemReview-create-db","number":53,"title":"create db table for menuitemreview","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/53"},{"author":{"id":"U_kgDOCVPcVQ","is_bot":false,"login":"matthewli10","name":""},"headRefName":"matthewli-get-endpoint","number":52,"title":"ML - create GET endpoint for single record in UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team01-s26-08/pull/52"}]
